import React from 'react';
import styles from './Conditions.module.scss';

function Conditions(props) {
    return (
        <div className={styles.policy}>
            <h2>1. À qui s’adressent les présentes Conditions Générales d’Utilisation ?</h2>
            <p>Chez Energy drink, comme défini dans l’empreinte de ce site Web, (ci-après « Red Bull GmbH » ou « Nous »), nous souhaitons mettre à la disposition de nos clients, de nos fans et de notre communauté les meilleurs produits, contenus et services disponibles à tout moment, sur nos pages Web et applications (Plateformes) et continuer à développer ces produits, contenus et services avec vous. Cependant, chaque coopération nécessite de définir un ensemble de règles de base claires afin d’orienter la manière dont nous interagissons les uns avec les autres et de définir les valeurs fondamentales. Les présentes Conditions Générales d’Utilisation ont pour but de définir le cadre général de notre relation à l’égard de nos produits, contenus et services gratuits, et forment ainsi la base commune sur laquelle nous pouvons nous appuyer pour travailler ensemble (Règles).</p>
            <h2>2. Champ d'application</h2>
            <p>Les présentes Conditions Générales d’Utilisation s’appliquent à l’utilisation de l’un quelconque de nos produits, contenus et services (Contenu) librement mis à disposition sur nos Plateformes. Cela inclut votre utilisation du Contenu, que vous visitiez et naviguiez sur nos pages Web et nos applications, que vous vous inscriviez à des événements, à des bulletins d’information ou à des offres similaires, que vous téléchargiez et diffusiez notre Contenu ou que vous vous inscriviez et créiez un compte.</p>
            <h2>3. Vos obligations en tant qu'utilisateur</h2>
            <p>Chez Energy drink, nous pensons qu’une collaboration et une interaction sociale en ligne réussies nécessitent de bonnes manières (nétiquette) et des règles de conduite. Notre Contenu est fourni uniquement pour votre usage personnel, ce qui signifie que vous ne pouvez pas l’utiliser à des fins commerciales ou à d’autres fins lucratives. Notre coopération est subordonnée à votre respect des lois applicables, de nos droits ou des droits de tiers et de votre utilisation du Contenu uniquement d’une manière conforme aux présentes Règles et implique que vous ne les anéantissiez, ne les endommagiez ou ne les exploitiez pas de toute autre manière.

                Nous croyons également à l’importance du respect mutuel et de la considération que nous avons à l’égard des autres. Par conséquent, tout contenu que vous publiez en utilisant nos services ne doit contenir aucune forme de discours haineux, diffamatoire ou susceptible de donner une image négative de nous ou d’une autre personne.</p>
            <h2>4. Fin de la coopération</h2>
            <p>En cas de dysfonctionnements dans notre relation, en particulier si vous enfreignez les présentes Règles, nous nous réservons le droit de mettre fin à cette coopération à tout moment.</p>
            <h2>5. Contenus et services Energy drink</h2>
            <h3>5.1 Tous les droits sur le Contenu appartiennent à Red Bull GmbH</h3>
            <p>L’ensemble du Contenu mis à disposition sur nos Plateformes, y compris le contenu et les services fournis par vous ou par des tiers, c’est-à-dire notamment tous les textes, logos, marques, graphiques, illustrations, sons, musiques et logiciels (y compris le logiciel d’accès) sont protégés par des droits d’auteur, des droits personnels, des modèles déposés, des brevets, des marques de commerce, des marques de service, des droits de conception, des droits des bases de données, des secrets industriels, des droits de confidentialité et autres droits similaires (« DPI »). Tous les droits de propriété intellectuelle existants afférents aux Plateformes et à son Contenu sont notre propriété ou nous avons été autorisés à les utiliser par leur titulaire. Tous les droits y afférents nous sont réservés ou, s’ils ont été fournis par un tiers, sont réservés aux tiers qui en sont titulaires (et ce, même si ledit contenu ou service n’est pas expressément identifié comme étant protégé par la loi ou déposé, ceci ne pouvant ni ne devant être interprété comme une renonciation de notre part, ou de la part de tiers concernés, aux droits de propriété intellectuelle afférents à ce contenu ou service, en totalité ou en partie). Vous n’êtes pas autorisé(e) à reproduire, copier, publier en ligne, publier à nouveau, diffuser, enregistrer, transmettre ou éditer tout contenu, document ou toute partie de ceux-ci sans avoir obtenu expressément, au préalable, notre autorisation écrite. Vous n’êtes pas non plus autorisé(e) à faire ou tenter de faire quoi que ce soit qui enfreindrait nos droits de propriété intellectuelle ou tout autre droit de propriété intellectuelle nous ayant été concédés sous licence ou dont des tiers sont propriétaires. Ceci s’applique également aux idées et concepts sur lesquels les Plateformes ou Contenus reposent, même s’ils ne sont protégés par aucun droit de propriété intellectuelle.</p>
            <h3>5.2 Votre licence d’utilisation de nos Plateformes et Contenus</h3>
            <p>détienne tous les droits sur le Contenu mis à disposition sur nos Plateformes, nous souhaitons vous permettre d’accéder facilement à nos Plateformes et Contenus, afin que vous puissiez explorer tout ce que nous avons à offrir. Par conséquent, nous vous accordons une licence limitée afin d’utiliser notre Contenu pour votre usage personnel uniquement. Cela signifie que vous pouvez jouir de notre Contenu en tant que particulier, que ce soit à la maison ou en déplacement. Toutefois, votre licence ne vous permet pas d’utiliser notre Contenu dans le cadre de vos idées commerciales ou de toute autre activité commerciale, ni de reproduire, modifier ou exploiter notre Contenu. Vous n’êtes pas non plus autorisé(e) à transférer cette licence à des tiers.
            </p>
            <h3>5.3 Contenu de tiers</h3>
            <p>Nos Plateformes peuvent utiliser ou intégrer du contenu numérique ou des services de prestataires tiers (« Contenu de Tiers »). Vous reconnaissez et acceptez que votre droit d’utiliser ces contenus ou services de tiers puisse être soumis à des conditions générales supplémentaires imposées par le tiers prestataire des services. Si vous n’acceptez pas ces conditions supplémentaires, vous ne serez pas autorisé(e) à utiliser les contenus ou services respectifs de tiers.</p>
            <h2>6. Caractéristiques particulières</h2>
            <h3>6.1 Favoris</h3>
            <p>Certaines de nos Plateformes vous permettent de mettre votre Contenu favori en signet, afin de pouvoir y accéder rapidement et facilement par la suite. Vous pouvez également utiliser cette fonctionnalité afin de vous tenir informé(e) de nos nouveaux et prochains Contenus. Cette fonctionnalité fait partie intégrante de notre processus de fourniture et de développement de notre Contenu.</p>
            <h3>6.2 Authentification unique</h3>
            <p>Energy drink vous offre également la possibilité de vous authentifier de façon unique pour accéder à certains services Energy drink. Vous pourrez consulter ici les conditions générales de vente applicables ainsi que d’autres informations.</p>
            <h3>6.3 Prestataires de services de pair-à-pair</h3>
            <p>
                Veuillez noter qu’en utilisant certaines de nos Plateformes et certains de nos Contenus, vous acceptez également que vos ressources Internet et de connectivité puissent être utilisées par notre prestataire de services de pair-à-pair (« Prestataire de Pair-à-pair »). Veuillez noter que bien que notre Prestataire de Pair-à-pair s’efforce de limiter cet effet, l’utilisation de vos ressources par notre Prestataire de Pair-à-pair peut réduire votre connexion Internet et votre vitesse de téléchargement, et peut augmenter votre consommation de données si vous disposez d’un forfait de connexion Internet limité. Le Prestataire de Pair-à-pair utilise vos ressources locales afin de conserver temporairement du contenu, télécharger du contenu pour d’autres utilisateurs et télécharger du contenu appartenant à différents utilisateurs, tout en exposant temporairement d’autres utilisateurs à votre adresse IP. Ce pair-à-pair permet un accès plus rapide à notre Contenu grâce au téléchargement simultané du même contenu par un nombre important d’utilisateurs (par exemple aux heures de pointe des événements en direct). Vous pouvez vous désinscrire du réseau de pair-à-pair avant d’accéder à chaque Contenu.
            </p>
        </div>
    );
}

export default Conditions;